export const WORK_ENDPOINTS = {
    GET_APPLIERS: "/work/get-new-appliers",
    APPROVE_WORKER: "/work/approve-worker",
    GET_WORKERS: "/work/get-workers",
    GET_ALL_WORKS: "/work/get-all-works",
    POST_WORK: "/work/post-work",
    APPLY_WORKER: "/work/apply-worker",
    BLOCK_WORKER: (id: string) => `/work/block-worker/${id}`,
    GET_MY_WORKS: "/work/get-my-works",
    UPDATE_WORK: (workId: string) => `/work/update-work/${workId}`,
    DELETE_MY_WORK: (workId: string) => `/work/delete-my-work/${workId}`,
    GET_WORKER_ASSIGNED_WORKS: "/work/worker-assigned-works",
    GET_WORKER_DASHBOARD_STATS: "/work/worker/dashboard-stats",
    ADMIN_WORK_STATS: "/work/admin/work-stats",
    GET_WORKER_PROFILE: "/work/worker/profile",
    GET_UPLOAD_SIGN: "/work/worker/profile-image/upload-signature",
    SAVE_WORKER_PROF_URI_FROM_CLOUD: "/work/worker/profile-image",
    UPDATE_WORKER_PROFILE: "/work/worker/profile",
    WORK_MEDIA_UPLOAD_SIGNATURE: "/work/work-media/upload-signature",
};